### ISSUE TITLE
Add support for Vault agent.

### ISSUE THREAD

**Issue by semrov** [TerryHowe/ansible-modules-hashivault#147]
Add support for authenticating with [Vault Agent](https://www.vaultproject.io/docs/agent/).

Add additional authentication type to VAULT_AUTHTYPE environment variable called 'Agent', which means 'pass authentication to Vault Agent'. In general there are two options available:
    1) No additional authentication data (like token, role id etc.) provided in environment:
          - Just pass request to Vault agent - agent is entirely responsible for authentication 
    2) Additional authentication data (like token, role id etc.) is provided in environment:
          - Pass provided data to Vault Agent, Vault Agent now uses authentication data provided in environment instead of these provided in Agent's configuration file 

That is exactly how Agent works.

For example: 
In case of: lookup('hashi_vault', 'secret={{ secret_path }}  url={{ vault_addr }}') 

1) No environment data provided:
    - Vault agent is completely responsible for authentication with Vault server (using it's own configuration)
2) Environment data (like VAULT_TOKEN) provided:
    -  hashi_vault module passes VAULT_TOKEN to agent. Agent now uses VAULT_TOKEN to authenticate with server.

For start only option 1) would be enough to implement.

Currently hashi_vault module throws exception if no authentication data provided in environment.

**Comment by drewmullen** [comment]
the `hashi_vault` lookup module is not managed by this repo. that is managed by [ansible/ansible](https://docs.ansible.com/ansible/latest/plugins/lookup/hashi_vault.html). its confusing because Terry has created a `hashivault` lookup function.

now, to your issue. what specifically would you want us to do? enable and setup the Agent? iirc, once the agent is up and running on a host, it merely provides you a token in a file (or env variable) so authentication would be just reading that file

if youre looking for help setting up an agent on a host, i have a role that you can use: https://github.com/drewmullen/ansible-vault-auto-auth. im pretty sure it only supports approle atm but feel free to open an issue there for more features (or a pr! :)

**Comment by semrov** [comment]
It seems I shoud repost this issue to ansible/ansible repo then. Closing this issue.
