### ISSUE TITLE
dependecy to module hvac - ansible-modules-hashivault is not self contained

### ISSUE THREAD

**Issue by xtermi2** [TerryHowe/ansible-modules-hashivault#23]
Hi,

when executing any vault task with this ansible module I get an ERROR:

> fatal: [10.248.71.17]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.248.71.17 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Zojwta/ansible_module_hashivault_init.py\", line 75, in <module>\r\n    from ansible.module_utils.hashivault import *\r\n  File \"/tmp/ansible_Zojwta/ansible_modlib.zip/ansible/module_utils/hashivault.py\", line 3, in <module>\r\nImportError: No module named hvac\r\n", "msg": "MODULE FAILURE", "rc": 0}

meaning on the target host I have to install the hvac python module which is not easily possible, because i have no internet connection on this machine where Vault is installed. So I can't use pip or any other package manager to install it over ansible. 

This module should be standalone runnable (self contained). Please include all your dependent python modules in your artifact.

thx
Andi

**Comment by TerryHowe** [comment]
While this might be convenient for you, it would be inconvenient for about everyone else and unexpected by everyone else.  Nearly all Python packages have package dependencies and load dependencies from pypi.  Obviously, you need to intall ansible and ansible-module-hashivault, so why not install hvac.  I assume you are downloading the gz files off pypi.

I situations I've been another approach I've sometimes seen is setting up your own software repo, but that is only useful if you have a lot of offline servers and a lot of software.

One other thing, that particular error can be cause by a lot of other things like a syntax error in the hosts or ansible.cfg file.

**Comment by xtermi2** [comment]
Maybe you misunderstood me or my explanation was not clear enough: Yes, on my control host i have to install ansible and all required modules, but on the target/remote host I don't have to (and I don't want to). That's exactly ansibles job, to copy the required environment to the target/remote host, and execute the job there. 
http://docs.ansible.com/ansible/dev_guide/developing_modules.html
http://docs.ansible.com/ansible/dev_guide/developing_modules_best_practices.html
Yes, it's not required, but best practice to have no external dependencies.

**Comment by TerryHowe** [comment]
Ah yeh I wasn't getting it. Can you target local host instead since
everything is installed there?

On Jul 13, 2017 12:36 PM, "AK" <notifications@github.com> wrote:

Maybe you misunderstood me or my explanation was not clear enough: Yes, on
my control host i have to install ansible and all required modules, but on
the target/remote host I don't have to (and I don't want to). That's
exactly ansibles job, to copy the required environment to the target/remote
host, and execute the job there.
http://docs.ansible.com/ansible/dev_guide/developing_modules.html
http://docs.ansible.com/ansible/dev_guide/developing_
modules_best_practices.html
Yes, it's not required, but best practice to have no external dependencies.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/TerryHowe/ansible-modules-hashivault/issues/23#issuecomment-315165187>,
or mute the thread

**Comment by xtermi2** [comment]
targeting localhost is fine, cause hvac was installed there as dependency of ansible-modules-hashivault.

**Comment by TerryHowe** [comment]
That is generally how it is intended to be used. From localhost

**Comment by TerryHowe** [comment]
On localhost I mean

**Comment by rdunklau** [comment]
Hello,

Sorry to reopen this old issue, but I would like to use this module on any target host, not only on localhost. Would it be possible to write this module the standard ansible way, ie self-contained ? 

Thank you !
