### ISSUE TITLE
Missing link in docs for hashivault_aws_auth_config_module

### ISSUE THREAD

**Issue by maishiroma** [TerryHowe/ansible-modules-hashivault#277]
Not sure if this is the right place to ask this, since the docs seem to be in a private repository? Regardless, I noticed that in the main module page for this Ansible module: https://terryhowe.github.io/ansible-modules-hashivault/modules/list_of_hashivault_modules.html, there is a broken link for `hashivault_aws_auth_config_module`. 

![Screen Shot 2020-08-11 at 11 54 09 AM](https://user-images.githubusercontent.com/19522250/89937133-88e77100-dbc9-11ea-95ad-b34138a24dce.png)

Thankfully, that page still exists if you edit the url to to said module: https://terryhowe.github.io/ansible-modules-hashivault/modules/hashivault_aws_auth_config_module. However, it seems that the title has a mistypo:
```
hashivault_aws_auth_role_create – Hashicorp Vault aws auth configure module
```

when it should say:
```
hashivault_aws_auth_config – Hashicorp Vault aws auth configure module
```

Not sure if that has anything to do with the broken link, but it is something that I found a little troubling when finding documentation for AWS auth for this Ansible module.

**Comment by drewmullen** [comment]
the issue is that the file name is incorrect and should actually be the same as the function name (which is also how ansible names the module): https://github.com/TerryHowe/ansible-modules-hashivault/blob/d5742daf0d931a1c7eb053c1fbfc22fd2aa5607b/ansible/modules/hashivault/hashivault_aws_auth_config.py#L13

there does not appear to be a module hashivault_aws_auth_config_module 

I havent used these modules to configure aws but if i compare it to how ive configured azure auth backends this may actually be what youre looking for @maishiroma `hashivault_aws_auth_role_create`

**Comment by maishiroma** [comment]
@drewmullen Ah interesting find on that. Let me test this out on my end and I'll get back to this issue to confirm if that method is the one that should be used/referenced instead.

**Comment by TerryHowe** [comment]
I think just the docs are wrong, `hashivault_aws_auth_config` should work.

**Comment by maishiroma** [comment]
I apologize for the late reply, but I just got around to test this, and I confirmed that using  `hashivault_aws_auth_config` is indeed the correct module to use for configurating the AWS auth endpoint. So yes, this is indeed a typo on the docs.
